### ISSUE TITLE
Toevoegen dummywaarden 

### ISSUE THREAD

**Issue by arthurtilkens** [bertvanovermeir/OTL#14]
Voor ieder attribuut een dummy waarde toevoegen. Conform de info op website wegenenverkeer.be.

**Comment by bertvanovermeir** [comment]
te onderzoeken, mogelijke oplossingen:
- extra rij met datatype
- dummy waarden "AI"
- dummy waarden prefix "dummy"
- kleurencode voor dummywaarden
