### ISSUE TITLE
probleem bestandsnaam eindigend op .0

### ISSUE THREAD

**Issue by AlecVerheyden1** [bertvanovermeir/OTL#15]
Indien de naam van het XLS bestand dat je wil exporteren uit de tool eindigt in bijvoorbeeld .0 dan wordt er een 0-bestand aangemaakt in plaats van een .xls bestand. Dit probleem kan je oplossen door in de naamgeving nog .xls toe te voegen.

**Comment by bertvanovermeir** [comment]
geen fix voorzien, kan intended zijn voor bepaalde users
