### ISSUE TITLE
Enkele suggesties/opmerkingen

### ISSUE THREAD

**Issue by arthurtilkens** [bertvanovermeir/OTL#24]
- beschrijvingen van de attributen niet altijd even handig. Bv. "technischeFiche.bestandsnaam" heeft als uitleg: "De naam van het Document inclusief de bestandsextensie, van de naam gescheiden door een punt." Opzich is dit nuttige info, maar voor complexe attributen ontbreekt de beschrijving van dat overkoepelende attribuut, in dit geval "technischeFische". Wat wordt er bedoeld met een technische fische? 

- Eventueel werken met typeURI's voor de eigenschappen, dat ze verwezen worden naar de website en dara de info per eigenschap makkelijk kunnen opzoeken! 
- Kleine suggestie om de definitie van het object zelf ook mee te geven. Dit moeten ze dan uiteraard verwijderen. Hoewel, als ze slim zijn klikken ze natuurlijk gewoon op de typeURI van dat object wat meegegeven kan worden.

**Comment by bertvanovermeir** [comment]
planned 4.3
