### ISSUE TITLE
SDF- opmaak STYLE met tekst kan niet

### ISSUE THREAD

**Issue by Ben-V-B** [bertvanovermeir/OTL#44]
er is een probleem als je een style wilt opmaken voor de SDF.
door het bestaan van de '[]' lege haakjes in de logical Property kan er geen enkele tekst gekoppeld worden aan de data velden.
![Knipsel](https://user-images.githubusercontent.com/127380757/223955325-ca9edc97-99f9-4197-8c72-0903f31380c8.PNG)
![Knipsel1](https://user-images.githubusercontent.com/127380757/223955376-cb35ff48-9cde-4f9b-8851-03ed826cf520.PNG)
![Knipsel2](https://user-images.githubusercontent.com/127380757/223955400-053941ae-ea62-4119-aee7-dcef272873f2.PNG)

**Comment by bertvanovermeir** [comment]
@rudewi Als we dit kunnen reproduceren vormt dat wel een probleem voor het SDF formaat in het algemeen, en moet de instructiebundel worden aangepast. Voor de tools zelf kan ik dit snel en efficient oplossen in één lijn.

**Comment by Ben-V-B** [comment]
Deze fout lijkt me met de de autocad Civil versie van 2024 van de baan te zijn
